app/models.py
from flask_login import UserMixin, AnonymousUserMixin
from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from . import login_manager
from datetime import datetime


class UserModel(UserMixin, db.Model):
    __tablename__='user'
    __table_args__ = {'sqlite_autoincrement': True}

    id = db.Column(db.BigInteger, primary_key=True)
    username = db.Column(db.String(128), unique=True, index=True)
    email = db.Column(db.String(128),unique=True, index=True)
    password_hash = db.Column(db.String(256))
    active = db.Column(db.Boolean, default=False)
    enable = db.Column(db.Boolean, default=True)
    role_id = db.Column(db.Integer, db.ForeignKey('role.id'))
    logs = db.relationship('LogModel', backref='user')

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def can(self, permission):
        # 判断用户是否具备某权限
        return self.role is not None and (self.role.permissions & permission) == permission

    def is_administrator(self):
        # 判断用户是否具备管理员权限
        return self.can(Permission.LINK | Permission.OTHER)


class LogModel(db.Model):
    __tablename__='log'
    __table_args__ = {'sqlite_autoincrement': True}
    id = db.Column(db.BigInteger, primary_key=True)
    user_id = db.Column(db.BigInteger, db.ForeignKey('user.id'))
    start_time = db.Column(db.DateTime, default=datetime.utcnow)
    end_time = db.Column(db.DateTime)
    trusted_ip = db.Column(db.String(64))
    trusted_port = db.Column(db.String(10))
    bytes_received = db.Column(db.BigInteger)
    bytes_sent = db.Column(db.BigInteger)
    finished = db.Column(db.Boolean, default=False)


class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False

    def is_administrator(self):
        return False

login_manager.anonymous_user = AnonymousUser

@login_manager.user_loader
def loaf_user(user_id):
    return UserModel.query.get(int(user_id))


class Permission:
    '''
    Permission Table
    '''

    ## Link to server via openvpn
    LINK = 0x01

    ## Other permission
    OTHER = 0x80


class RoleModel(db.Model):
    '''
    User Roles Table
    '''
    __tablename__='role'
    id = db.Column(db.Integer, primary_key=True)
    # 该用户角色名称
    name = db.Column(db.String(164))
    # 该用户角色是否为默认
    default = db.Column(db.Boolean, default=False, index=True)
    # 该用户角色对应的权限
    permissions = db.Column(db.Integer)
    # 该用户角色和用户的关系
    # 角色为该用户角色的所有用户
    users = db.relationship('UserModel', backref='role', lazy='dynamic')

    @staticmethod
    def insert_roles():
        """
        创建用户角色
        """
        roles = {
            # 定义了两个用户角色(User, Admin)
            'User': (Permission.LINK, True),
            'Admin': (Permission.LINK |
                      Permission.OTHER, False)
        }
        for r in roles:
            role = RoleModel.query.filter_by(name=r).first()
            if role is None:
                # 如果用户角色没有创建: 创建用户角色
                role = RoleModel(name=r)
            role.permissions = roles[r][0]
            role.default = roles[r][1]
            db.session.add(role)
            db.session.commit()

app/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired, Length


class AddUserForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(1,48)])
    password = StringField('Password' ,validators=[DataRequired(), Length(4)])
    #role_id = IntegerField('Role ID', validators=[DataRequired()])
    submit = SubmitField('Add')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_login import LoginManager
from flask_moment import  Moment


# plugin decelar
bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
moment = Moment()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # plugin init
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    moment.init_app(app)

    # add-on route
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth
    app.register_blueprint(auth, url_prefix='/auth')

    from .admin import admin
    app.register_blueprint(admin, url_prefix='/admin')

    return app

from .api import Api

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin',__name__)

from . import views

app/admin/utils/__init__.py
from openvpn_status import parse_status
from flask import current_app


class utils:
    def __init__(self):
        self.logfile = open(current_app.config['OPENVPN_LOGFILE'])
        if not self.logfile:
            current_app.logger.warning("OpenVPN logfile error: %s open faild." % current_app.config['OPENVPN_LOGFILE'])
        else:
            current_app.logger.info('Openvpn logfile open success')

    def get_user(self):
        status = parse_status(self.logfile.read())
        return status.client_list

app/admin/views.py
from . import admin
from .forms import AddUserForm
from ..decorator import admin_required
from .utils import utils
from flask import render_template
from ..models import UserModel
from app import db
from flask import flash, request

@admin.route('/')
@admin_required
def index():
    type = request.args.get('type')
    if not type:
        type = 'user_list'

    if type == 'user_list':
        users = UserModel.query.order_by(UserModel.id).all()
        return  render_template('admin/user_list.html', title='用户列表', users=users)
    # tool = utils()
    # users = tool.get_user()
    # print(users)
    # return render_template('admin/index.html', users=users)

@admin.route('/add_user', methods=['GET','POST'])
@admin_required
def add_user():
    form = AddUserForm()

    if form.validate_on_submit():
        if UserModel.query.filter_by(username=form.username.data).first():
            flash('User: %s already exist.' % form.username.data)
            return render_template('admin/add_user.html', form=form)

        user = UserModel(username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User: %s add successful, now can login via openvpn or web' % user.username)

    return render_template('admin/add_user.html', form=AddUserForm())

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views, errors

app/main/views.py
from flask import render_template, session, redirect, url_for, current_app
from flask_login import current_user, login_required
from . import main
from ..models import UserModel as User
from ..models import LogModel as Log


@main.route('/', methods=['GET'])
def index():
    return render_template('index.html')


@main.route('/user/<id>')
@login_required
def user(id=None):
    if not id:
        user = current_user
    else:
        user = User.query.get_or_404(id)

    current = Log.query.filter_by(finished=False, user=user).first()
    logs = Log.query.filter_by(user=user,finished=True).all()
    return render_template('user.html',user=user,logs = logs, current=current)


@main.route('/user')
@login_required
def user_info():
    return user(current_user.id)


@main.route('/download')
@login_required
def download():
    return render_template('download.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css') }}">

    <!-- Custom styles for this template -->
{#    <link href="justified-nav.css" rel="stylesheet">#}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
{#    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>#}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
      {{ moment.include_jquery() }}
      {{ moment.include_moment() }}

        <!--使用中文,默认是英语的-->
　　   {{ moment.lang("zh-CN") }}
  </head>

  <body>

      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">PyOpenVPN Web</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{{ url_for('main.download') }}">下载中心</a></li>
              <li><a href="#">关于</a></li>
                {% if current_user.is_administrator() %}
                    <li class="btn-warning"><a href="{{ url_for('admin.index') }}">管理员</a> </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if  current_user.is_authenticated %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">你好,{{ current_user.username }}<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ url_for('main.user_info') }}">用户信息</a> </li>
                            <li><a href="{{ url_for('auth.logout') }}">注销</a></li>
                            <li><a href="#">管理账户</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">充值中心</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">登录</a> </li>
                {% endif %}
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
      <div class="container-fluid">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}

        {% block page %}{% endblock %}

         <!-- Site footer -->
      <div class="footer">
        <p class="text-center">Copyright &copy; Beny Fu 2014-2017</p>
      </div>
    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
{#    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>#}
  <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
  <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

  </body>
</html>

app/templates/download.html
{% extends 'base.html' %}
{% block page %}
    <div class="row">
        <div class="col-md-4">
            <h2>联通3g-web</h2>
            <p>使用时请切换APN为3g-wap模式 </p>
            <p><a class="btn btn-default" href="http://home.huayuebox.com:88/owncloud/index.php/s/Mf1NvRpnTIpeQWd/download" role="button">下载 &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>移动</h2>
            <p>敬请期待...</p>
            <p><a class="btn btn-default" href="#" role="button">下载 &raquo;</a></p>
       </div>
        <div class="col-md-4">
            <h2>电信</h2>
            <p>敬请期待...</p>
            <p><a class="btn btn-default" href="#" role="button">下载 &raquo;</a></p>
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block page %}
<!-- Jumbotron -->
      <div class="jumbotron">
        <h1>新线路推出!</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet.</p>
        <p><a class="btn btn-lg btn-success" href="#" role="button">了解详情</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-lg-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>



{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page %}
{#    <div class="row">#}
{#    <div class="col-md-offset-2 page-header">#}
{#    <h1>Login</h1>#}
{#</div>#}
{#<div class="col-md-offset-2 col-md-8">#}
{#    {{ wtf.quick_form(form) }}#}
{#    <br>#}
{#    <p>Forgot your password? <a href="{{ url_for('auth.password_reset_request') }}">Click here to reset it</a>.</p>#}
{#    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>#}
{#</div>#}
{#    </div>#}
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form class="form-signin" role="form" method="post">
        <h2 class="form-signin-heading">请登录</h2>
        {{ form.hidden_tag() }}
        <input class="form-control" id="username" placeholder="用户名" name="username" required type="text" value="">
{#        <input type="text" class="form-control" placeholder="用户名" id="username" required autofocus>#}
        <input class="form-control" id="password" placeholder="密码" name="password" required type="password" value="">
{#        <input type="password" class="form-control" placeholder="密码" id="password" required>#}
        <div class="checkbox">
          <label>
            {{ form.remember_me()|safe }} {{form.remember_me.label.text|safe}}
          </label>
        </div>
        <div class="btn-group">
            <button class="btn btn-lg btn-primary" type="submit">登录</button>
            <button class="btn btn-lg btn-info" type="button">注册</button>
        </div>

      </form>
        </div>
    </div>


{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page %}
    <div class="row">
    <div class="col-md-offset-2 col-md-8 page-header">
        <h1>Register</h1>
    </div>

    <div class="col-sm-offset-2 col-md-8">
        {{ wtf.quick_form(form) }}
        <br>
    </div>
    </div>
{% endblock %}

app/templates/user.html
{% extends 'base.html' %}
{% block page %}

    <div class="page-header">
        <h1>{% if user.username %}{{ user.username }} {% if user.enable %}<span class="badge">Enable</span>{% else %}<span class="badge label-danger">Disable</span>{% endif %} {% else %}用户{% endif %}</h1>
    </div>

    {% if current %}
        <h1>正在连接</h1>
        <li>IP:{{ current.trusted_ip }}</li>
        <li>开始时间:{{ moment(current.start_time).format('LLL') }}</li>
    {% endif %}
    <div class="row">
    <table class="table table-condensed">
    <caption>登录记录</caption>
    <thead>
        <tr>
          <th>接入IP</th>
            <th>开始时间</th>
            <th>结束时间</th>
            <th>使用流量</th>
        </tr>
      </thead>
    {% for log in logs %}
        <tr>
          <td>{{ log.trusted_ip }}</td>
          <td>{{ moment(log.start_time).format('LLL') }}</td>
          <td>{{ moment(log.end_time).format('LLL') }}</td>
            <td>{{ format_bytes(log.bytes_received + log.bytes_sent) }}</td>
        </tr>
    {% endfor %}
    </table>
    </div>
{% endblock %}